In [7]:
# Author        : Cow Cheng
# Date          : 30/06/2024
# Description   : Creating edgelist for length property of edge from the raw edges information

In [8]:
import os
from pathlib import Path

ROOT_DIR = Path(os.getcwd()).parent.parent.absolute().__str__()

In [9]:
import pandas as pd

edges_df = pd.read_csv(filepath_or_buffer=f"{ROOT_DIR}/data/raw/osm_edges_info.csv")
edges_df

,u,v,key,osmid,oneway,lanes,name,highway,reversed,length,junction,bridge,ref,maxspeed,tunnel,access,service,area,geometry
0,33004487,10813125727,0,102506130,True,3.0,彌敦道 Nathan Road,primary,False,48.365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710536..."
1,33004487,9125470653,0,102506142,True,2.0,眾坊街 Public Square Street,secondary,False,1.845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710767..."
2,33004488,6357916699,0,102640426,True,3.0,彌敦道 Nathan Road,primary,False,11.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170737..."
3,33004488,1151084822,0,250489279,True,2.0,窩打老道 Waterloo Road,primary,False,10.668,intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170620..."
4,34971941,332248875,0,493744605,True,2.0,加士居道天橋 Gascoigne Road Flyover,trunk,False,43.118,NaN,yes,5.0,50.0,NaN,NaN,NaN,NaN,"LINESTRING (114.1673899 22.3106905, 114.167470..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7053,11880893092,11880893093,0,987256892,False,1.0,NaN,service,False,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171624..."
7054,11880893092,9125470644,0,987256892,False,1.0,NaN,service,True,7.362,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171708..."
7055,11880893093,11880893092,0,987256892,False,1.0,NaN,service,True,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.171624 22.3112437, 114.1716736..."
7056,11880893105,6521288995,0,150801664,False,NaN,石壁道 Cliff Road,residential,False,2.668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171830..."
7057,11880893105,4571243168,0,150801664,False,NaN,石壁道 Cliff Road,residential,True,2.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171863..."

In [10]:
edges_df = edges_df.loc[:, ["u", "v", "length"]]
edges_df

                u            v  length
0        33004487  10813125727  48.365
1        33004487   9125470653   1.845
2        33004488   6357916699  11.143
3        33004488   1151084822  10.668
4        34971941    332248875  43.118
...           ...          ...     ...
7053  11880893092  11880893093   7.312
7054  11880893092   9125470644   7.362
7055  11880893093  11880893092   7.312
7056  11880893105   6521288995   2.668
7057  11880893105   4571243168   2.248

[7058 rows x 3 columns]

In [11]:
edges_list = edges_df.values.tolist()
for edge in edges_list:
    edge[0] = int(edge[0])
    edge[1] = int(edge[1])
    edge[2] = edge[2]
edges_list

[[33004487, 10813125727, 48.365],
 [33004487, 9125470653, 1.845],
 [33004488, 6357916699, 11.143],
 [33004488, 1151084822, 10.668],
 [34971941, 332248875, 43.118],
 [245088212, 5135751883, 6.684],
 [245088214, 8795975506, 6.073],
 [274242693, 332243940, 9.945],
 [274242694, 4501965596, 14.687],
 [274242695, 3230279839, 21.355],
 [274242705, 274242708, 417.954],
 [274243013, 274243014, 182.805],
 [274243014, 4773727051, 42.91],
 [274243015, 8446511187, 83.523],
 [274243016, 1181846034, 47.385],
 [274243016, 8406879034, 9.445],
 [274243017, 332242393, 32.587],
 [274243018, 10566992992, 27.382],
 [274243083, 332233448, 21.63],
 [274243086, 5103661134, 19.105],
 [274243086, 5103661131, 18.853],
 [275908396, 10566992979, 10.663],
 [275909256, 6374553590, 101.106],
 [275909450, 7305838958, 26.995],
 [275909450, 7305838955, 16.145],
 [275935771, 7600185392, 9.874],
 [275944916, 4773693609, 7.402],
 [275945320, 9766361634, 7.366],
 [275945418, 3230274782, 4.894],
 [275945418, 9766365660, 19.025],
 [275945538, 11235236460, 6.056],
 [275945538, 10565387068, 7.374],
 [275945653, 10726301482, 56.492],
 [275945763, 10211498580, 11.252],
 [275945763, 3919865758, 128.083],
 [276372857, 6357916383, 52.42],
 [276372857, 1151084911, 10.724],
 [276373355, 6357916373, 50.107],
 [276377951, 11235236461, 81.833],
 [278948068, 1168316016, 9.49],
 [278948068, 6370253655, 20.145],
 [278948235, 10786928815, 4.022],
 [278948607, 6271340027, 15.656],
 [278948608, 1184307108, 20.751],
 [278948608, 332254414, 59.967],
 [278948609, 5255598058, 8.4],
 [278948759, 2640738083, 6.123],
 [278948832, 278948833, 29.668],
 [278948833, 5255598053, 7.904],
 [278948926, 6605085116, 11.427],
 [278948926, 5012933247, 8.059],
 [278948927, 5255598054, 34.388],
 [278948927, 5255598074, 4.269],
 [278948933, 439179847, 2.464],
 [278948934, 8044314666, 3.437],
 [278948999, 8044314690, 7.963],
 [278948999, 278949000, 84.107],
 [278949000, 278949001, 19.698],
 [278949000, 278948999, 84.107],
 [278949001, 278949000, 19.698],
 [279076776, 8764628282, 10.636],
 [279076776, 6550920169, 10.008],
 [288991082, 9893206659, 50.832],
 [288991083, 1172166327, 36.216],
 [288991084, 6777002698, 79.294],
 [288991123, 5029510785, 37.632],
 [288991123, 1962192579, 25.056],
 [288991127, 1962191597, 7.783],
 [288991127, 5029510779, 8.139],
 [288991129, 6052460354, 30.132],
 [288991129, 1962191505, 29.437],
 [288991131, 5118308284, 16.932],
 [288991131, 1172166329, 22.832],
 [288991132, 5118308285, 5.148],
 [288991132, 5118308284, 12.005],
 [288991202, 1172166326, 8.511],
 [288991202, 5029495350, 41.217],
 [288991212, 1295862825, 19.831],
 [288991212, 493883921, 30.263],
 [288991212, 1172166356, 25.669],
 [288991213, 1295862822, 15.723],
 [288991213, 1295862825, 13.963],
 [288991214, 332232638, 61.645],
 [288991214, 1295862839, 12.025],
 [288991218, 1962192639, 15.531],
 [288991218, 1962192676, 15.248],
 [288991218, 6266394644, 7.825],
 [288991219, 7154099552, 23.302],
 [288991219, 5029510784, 12.112],
 [288991219, 7154099554, 8.131],
 [288991220, 5118308280, 60.71],
 [288991220, 5029510780, 29.649],
 [288991221, 1962191716, 9.386],
 [288991221, 5118308280, 11.405],
 [288991222, 5029510778, 8.35],
 [288991222, 1962191597, 18.574],
 [288991223, 5118308283, 8.702],
 [288991223, 5118308286, 7.178],
 [288991224, 8396898511, 7.254],
 [288991224, 8081586137, 11.127],
 [288991224, 6277201384, 5.709],
 [288991681, 6176166200, 9.897],
 [288991681, 6176166201, 10.351],
 [288991682, 5118308267, 12.258],
 [288991682, 7597784320, 10.02],
 [288991682, 6039377373, 17.115],
 [288991740, 2868161557, 20.663],
 [288991741, 6364822864, 16.468],
 [288991742, 2086704742, 45.581],
 [288991742, 1182677912, 11.776],
 [288991776, 3230279162, 30.854],
 [288991777, 288991776, 25.965],
 [288991796, 1168066109, 8.466],
 [288991796, 9553739297, 53.143],
 [288991859, 4353561377, 63.293],
 [288991960, 288991859, 25.214],
 [288991961, 1640472777, 20.923],
 [288991961, 4858602289, 6.739],
 [288992106, 1640472750, 60.26],
 [288992206, 1640472741, 43.632],
 [288994875, 1640472834, 9.589],
 [288994875, 6886397805, 4.687],
 [288994882, 5103568431, 6.951],
 [288994882, 3200153661, 10.243],
 [288994965, 7859225560, 5.465],
 [288995086, 288995087, 8.41],
 [288995087, 7859225566, 6.252],
 [288995158, 3696283366, 3.697],
 [288995217, 4858447071, 4.63],
 [288996266, 7605392237, 15.354],
 [288996266, 7605392232, 13.791],
 [288996632, 288994882, 18.605],
 [288996657, 6886397800, 12.725],
 [289337490, 7575216225, 21.217],
 [289337490, 4858447073, 11.009],
 [308473171, 3230274026, 8.047],
 [308473171, 3230274006, 9.929],
 [308473172, 3230274170, 9.846],
 [308473172, 3230274041, 11.835],
 [308473173, 3230274023, 11.055],
 [308473173, 3230274192, 11.529],
 [308473175, 3230274366, 11.066],
 [308473175, 3230274296, 12.984],
 [308473176, 11134510106, 41.632],
 [308473177, 1183092765, 26.235],
 [308473177, 1151084890, 74.204],
 [308473178, 11134374501, 24.427],
 [308473179, 11134374504, 44.207],
 [308473179, 11134374500, 7.414],
 [308473179, 11134374497, 65.174],
 [308473180, 6260814403, 10.962],
 [308473180, 10804883515, 24.039],
 [308473181, 3230277085, 7.701],
 [308473182, 3230277492, 0.683],
 [308473182, 3230277353, 10.056],
 [308473183, 3230277355, 9.495],
 [308473183, 3230277483, 8.306],
 [308473185, 3230277719, 7.953],
 [308473185, 3230277610, 7.524],
 [308473186, 10825885939, 5.001],
 [308473186, 10181859559, 7.864],
 [308473186, 3230278485, 6.46],
 [308473187, 3230278507, 11.806],
 [308473188, 3230278501, 15.397],
 [308473188, 11235236463, 53.247],
 [308473189, 11196264030, 17.924],
 [308473190, 3230280848, 12.534],
 [308473190, 3230280999, 8.507],
 [308473191, 3230280976, 11.342],
 [308473191, 6364821073, 16.95],
 [308473192, 3230281110, 10.807],
 [308473193, 7205061372, 7.141],
 [308473193, 7205061371, 7.516],
 [308473195, 10250932206, 23.371],
 [308473419, 4501975098, 45.02],
 [308473420, 11232787248, 8.402],
 [308473420, 11134510116, 10.148],
 [308473422, 9953781642, 8.293],
 [308473422, 9953781649, 8.345],
 [308473423, 3176514544, 19.478],
 [308473424, 7983295859, 10.911],
 [308473424, 1151084860, 11.402],
 [308473425, 9067018578, 6.294],
 [308473426, 10825885963, 5.503],
 [308473427, 3230280089, 8.173],
 [308473429, 4862720941, 3.859],
 [308473429, 11235236471, 3.466],
 [308473546, 11248659125, 99.607],
 [308473546, 1178971365, 198.682],
 [308473546, 7205249277, 4.824],
 [316731588, 10864964066, 4.138],
 [316731590, 8789236514, 4.64],
 [316731591, 8789236510, 7.75],
 [316731592, 11406997370, 12.557],
 [316731592, 4292132285, 45.145],
 [316731592, 4292143906, 43.252],
 [331258075, 1168315954, 6.699],
 [331258075, 6374553575, 17.016],
 [331258761, 7257383508, 7.821],
 [331258761, 7257383490, 20.338],
 [331258761, 4773779469, 20.717],
 [331258764, 991294650, 41.504],
 [331269944, 332251255, 47.352],
 [331269982, 7242599215, 8.12],
 [331269982, 6236308354, 41.2],
 [331271265, 4773779481, 12.761],
 [331271265, 4773716027, 8.609],
 [331271928, 2389070841, 3.798],
 [332227468, 4858602284, 7.708],
 [332227468, 6364822991, 12.805],
 [332227469, 332227468, 45.646],
 [332227470, 332227469, 8.176],
 [332227471, 9893504824, 6.808],
 [332228049, 332233734, 40.645],
 [332228049, 11229660893, 5.969],
 [332228052, 5133915668, 21.586],
 [332228052, 5133915667, 16.184],
 [332228053, 4501965600, 9.858],
 [332228053, 4501965601, 2.692],
 [332228054, 5133915669, 5.453],
 [332228055, 332228056, 17.996],
 [332228056, 1182677867, 14.689],
 [332228056, 332228057, 12.347],
 [332228057, 1640472754, 11.705],
 [332228057, 6886392425, 44.95],
 [332228058, 4858594757, 6.262],
 [332228059, 6886392427, 7.394],
 [332228061, 7257383509, 13.538],
 [332230218, 332228059, 13.799],
 [332230894, 332227469, 7.261],
 [332230895, 332230894, 18.32],
 [332231811, 5118069110, 8.209],
 [332231811, 6364822869, 17.254],
 [332231898, 332231899, 9.822],
 [332231899, 2868161561, 13.053],
 [332231899, 2868161562, 15.844],
 [332231922, 1182677790, 8.595],
 [332231923, 332231922, 8.601],
 [332231924, 332231923, 8.6],
 [332231925, 332231924, 6.702],
 [332232288, 2868161559, 8.866],
 [332232290, 1182677772, 12.838],
 [332232291, 9553739289, 14.413],
 [332232291, 1182677796, 6.516],
 [332232292, 288991961, 15.385],
 [332232293, 332232292, 13.021],
 [332232294, 6984911314, 6.521],
 [332232295, 6984911302, 6.521],
 [332232638, 1172166308, 28.809],
 [332232638, 288991214, 61.645],
 [332232732, 1956604873, 14.747],
 [332232732, 1172166429, 13.025],
 [332232732, 1956604863, 10.15],
 [332232763, 332232764, 20.7],
 [332232763, 6777002695, 70.257],
 [332232763, 6776978979, 8.957],
 [332232764, 332232765, 27.402],
 [332232764, 332232763, 20.7],
 [332232765, 332232766, 26.153],
 [332232765, 332232764, 27.402],
 [332232766, 5118308287, 8.077],
 [332232766, 332232765, 26.153],
 [332233250, 2868161565, 29.899],
 [332233250, 5118069109, 13.154],
 [332233253, 1168183739, 8.949],
 [332233448, 9553739296, 44.163],
 [332233448, 8154269374, 73.602],
 [332233449, 9553739295, 6.735],
 [332233450, 9553739291, 6.803],
 [332233452, 5054347008, 13.944],
 [332233734, 6776978971, 19.346],
 [332234423, 332234424, 42.773],
 [332234424, 9553982032, 31.341],
 [332234425, 5118039272, 26.754],
 [332234452, 332234425, 14.347],
 [332235143, 9553982035, 71.773],
 [332236247, 11242686010, 17.474],
 [332236248, 3230279914, 15.979],
 [332236250, 332236251, 12.861],
 [332236251, 332236252, 13.148],
 [332236252, 9553739290, 11.597],
 [332236302, 332236591, 12.595],
 [332236303, 5118039270, 10.312],
 [332236564, 4944491510, 11.029],
 [332236591, 5118039267, 12.099],
 [332236658, 3230278791, 16.509],
 [332236659, 493175666, 18.307],
 [332236871, 4944491509, 10.05],
 [332237002, 332237036, 12.121],
 [332237036, 332236871, 11.147],
 [332237192, 332237262, 31.155],
 [332237199, 6374553508, 4.251],
 [332237238, 332237192, 10.425],
 [332237262, 4773727049, 88.986],
 [332237288, 3270208461, 7.89],
 [332238310, 11129305619, 46.763],
 [332238480, 6389190616, 47.443],
 [332238481, 11214989179, 11.274],
 [332238481, 11214989167, 7.902],
 [332239185, 5133960459, 5.356],
 [332239185, 1180686912, 14.392],
 [332240179, 11453018971, 44.755],
 [332240248, 6389233142, 17.031],
 [332240697, 1181846062, 24.073],
 [332240700, 4773779472, 4.667],
 [332241860, 5020696807, 2.723],
 [332241861, 10566992988, 20.29],
 [332241861, 10566992986, 17.703],
 [332241870, 1172757618, 15.524],
 [332241870, 332243716, 40.766],
 [332241887, 8559094354, 2.046],
 [332241978, 1181846107, 10.196],
 [332241978, 7257383506, 23.626],
 [332241980, 7257383504, 4.701],
 [332242040, 6984393973, 19.804],
 [332242040, 6984393970, 4.042],
 [332242116, 4773779436, 5.075],
 [332242333, 6576843537, 6.366],
 [332242333, 7159249733, 9.396],
 [332242336, 1161863870, 30.342],
 [332242353, 4773779431, 8.254],
 [332242393, 274243018, 203.349],
 [332242579, 6370140256, 45.781],
 [332242579, 7242599236, 15.344],
 [332242620, 1181846148, 10.119],
 [332242620, 4123241553, 25.95],
 [332242753, 10848289257, 102.809],
 [332242753, 1178971331, 57.498],
 [332242754, 332251620, 110.665],
 [332242754, 332242753, 47.938],
 [332242755, 5035288921, 2.124],
 [332242755, 1178971377, 21.883],
 [332242765, 332243937, 7.692],
 [332243000, 6264275960, 3.487],
 [332243002, 332253240, 68.956],
 [332243003, 288991796, 16.73],
 [332243003, 1168066104, 41.77],
 [332243005, 4860492619, 4.753],
 [332243007, 7205257472, 17.514],
 [332243088, 6357916689, 15.566],
 [332243088, 6063179965, 4.369],
 [332243513, 8273466961, 49.874],
 [332243571, 332246717, 36.009],
 [332243585, 4501974987, 98.746],
 [332243716, 332241870, 40.766],
 [332243716, 332241978, 62.653],
 [332243937, 7257383515, 7.702],
 [332243938, 7388719094, 69.025],
 [332243939, 274242693, 19.29],
 [332243940, 3230277782, 10.958],
 [332243941, 7388719090, 71.124],
 [332244016, 8272842740, 135.335],
 [332244018, 3696262782, 52.54],
 [332244341, 274243083, 48.561],
 [332246270, 6176174000, 8.905],
 [332246273, 1168380690, 41.499],
 [332246717, 34971941, 124.627],
 [332246756, 5133754167, 44.371],
 [332247607, 6611651275, 11.323],
 [332247608, 332248687, 52.82],
 [332248212, 332248213, 57.016],
 [332248213, 629161529, 52.457],
 [332248214, 6702444348, 45.591],
 [332248685, 332248700, 154.818],
 [332248686, 5118308275, 45.047],
 [332248687, 332248686, 85.52],
 [332248700, 332243513, 39.311],
 [332248875, 332248821, 22.479],
 [332250570, 10786928832, 6.809],
 [332251015, 3230283954, 14.559],
 [332251015, 1168183637, 11.065],
 [332251063, 5103661127, 6.2],
 [332251063, 5103661126, 5.733],
 [332251094, 11181151128, 10.483],
 [332251094, 4860492620, 8.564],
 [332251253, 332251620, 47.939],
 [332251253, 11178396848, 121.892],
 [332251253, 332242753, 110.778],
 [332251254, 332251484, 63.615],
 [332251254, 3391012792, 125.472],
 [332251255, 9067018573, 43.903],
 [332251256, 7205249279, 21.643],
 [332251256, 7207625693, 120.23],
 [332251257, 332251256, 57.928],
 [332251257, 10181839350, 12.025],
 [332251373, 1182677910, 34.374],
 [332251374, 3230283899, 11.858],
 [332251374, 3230283560, 27.543],
 [332251375, 9067018588, 8.95],
 [332251375, 9067018571, 10.889],
 [332251376, 7207625692, 13.922],
 [332251377, 3696264071, 10.756],
 [332251377, 10198945171, 5.831],
 [332251377, 10181839356, 6.779],
 [332251378, 3691165231, 15.844],
 [332251484, 10203538055, 9.301],
 [332251484, 1442088610, 29.475],
 [332251500, 9135398607, 6.364],
 [332251605, 3391012791, 34.965],
 [332251620, 6236308350, 36.58],
 [332251664, 332251373, 19.228],
 [332251664, 11177196758, 20.72],
 [332251667, 7454080527, 11.186],
 [332251667, 5133880779, 27.856],
 [332251683, 332251682, 44.121],
 [332251828, 11134374487, 63.656],
 [332252247, 7597823394, 26.498],
 [332252247, 1182950283, 19.528],
 [332253240, 1168315922, 61.842],
 [332253240, 8438621459, 14.585],
 [332253310, 3230275941, 11.867],
 [332253310, 3230275869, 7.047],
 [332253311, 3230276002, 11.054],
 [332253311, 3230275952, 8.503],
 [332253312, 3230275924, 10.868],
 [332253312, 3230276003, 11.616],
 [332253313, 3230276216, 8.403],
 [332253329, 7159812414, 4.96],
 [332253329, 1185400641, 47.158],
 [332253331, 10825885941, 5.084],
 [332253333, 8192075924, 45.229],
 [332253494, 6880235602, 5.23],
 [332253494, 4501974988, 65.181],
 [332253631, 3230274239, 73.035],
 [332254414, 4355051555, 26.586],
 [332254415, 3691187062, 7.448],
 [332254415, 1162875764, 4.164],
 [334647674, 2861669114, 11.421],
 [334647674, 11104977107, 11.766],
 [334647889, 2861666795, 26.864],
 [334647890, 11104980151, 11.019],
 [334647891, 2861666800, 48.643],
 [334647892, 2861669103, 31.028],
 [334647893, 334647894, 69.556],
 [334647894, 2861669109, 21.508],
 [334647895, 11104980142, 33.073],
 [334647896, 11104980135, 8.142],
 [334647897, 4502010708, 24.703],
 [334647899, 334652200, 46.009],
 [334648400, 1168315957, 5.697],
 [334648405, 334648629, 45.367],
 [334648625, 6989122616, 8.329],
 [334648625, 1168315919, 34.023],
 [334648626, 6357916691, 65.652],
 [334648627, 1168315967, 46.734],
 [334648629, 334648627, 56.855],
 [334648722, 334651133, 52.748],
 [334648723, 334651132, 28.808],
 [334648727, 2861669101, 25.59],
 [334649581, 11081087759, 25.282],
 [334649727, 334649852, 57.692],
 [334649728, 8767974619, 36.722],
 [334649729, 2868161551, 5.48],
 [334649849, 334650280, 34.185],
 [334649850, 4501965609, 12.762],
 [334649851, 2866714638, 18.97],
 [334649851, 2866714639, 19.728],
 [334649852, 334649851, 106.026],
 [334650236, 11104980140, 28.496],
 [334650280, 2866714635, 10.76],
 [334650280, 2866714634, 10.543],
 [334650313, 339053515, 9.232],
 [334650313, 339053461, 8.984],
 [334650570, 1172166386, 23.955],
 [334650572, 334650573, 32.511],
 [334650573, 334650574, 47.688],
 [334650574, 9125470648, 50.282],
 [334650575, 1168315927, 9.657],
 [334650654, 9125470651, 14.214],
 [334650656, 1172166367, 10.789],
 [334650656, 7553815435, 13.657],
 [334650889, 334650890, 14.346],
 [334650890, 334650891, 80.202],
 [334650891, 6370217679, 24.205],
 [334650892, 334650893, 62.146],
 [334650893, 4501965605, 22.698],
 [334650906, 7859225563, 5.071],
 [334650907, 2868161575, 54.903],
 [334650908, 8767974621, 23.966],
 [334651084, 2868161570, 10.578],
 [334651084, 2868161571, 10.227],
 [334651129, 334651084, 94.964],
 [334651130, 7539621741, 3.64],
 [334651131, 7270937151, 9.239],
 [334651132, 334648722, 29.754],
 [334651133, 11105007273, 131.4],
 [334651138, 2868161552, 17.702],
 [334651139, 2868161550, 16.05],
 [334651140, 11104975395, 8.971],
 [334651141, 11104975391, 11.626],
 [334651141, 11104975394, 13.712],
 [334651192, 8909807442, 14.232],
 [334651192, 7605392237, 7.065],
 [334651193, 11462479066, 3.57],
 [334651193, 7605409499, 11.184],
 [334651194, 334651193, 10.466],
 [334651195, 5052279540, 8.242],
 [334651195, 6776978974, 7.594],
 [334651201, 334651131, 10.341],
 [334651203, 334651201, 11.073],
 [334652024, 334652025, 88.665],
 [334652025, 2832941849, 64.129],
 [334652026, 11104977129, 13.517],
 [334652027, 11104980131, 62.227],
 [334652029, 11104980139, 37.601],
 [334652030, 11104980143, 32.06],
 [334652032, 11104980146, 15.956],
 [334652033, 2861669108, 68.046],
 [334652034, 334652035, 31.386],
 [334652035, 334652036, 59.527],
 [334652036, 334652037, 46.824],
 [334652037, 334652038, 32.889],
 [334652038, 339053444, 9.757],
 [334652200, 11104977130, 44.569],
 [334652201, 334652202, 64.362],
 [334652202, 2832941850, 86.734],
 [334653504, 334650908, 34.283],
 [334653511, 2868161573, 43.88],
 [339050813, 8766021731, 9.543],
 [339050887, 7553034785, 13.73],
 [339050887, 339050888, 10.675],
 [339050888, 339050889, 24.766],
 [339050889, 2861669102, 4.885],
 [339050890, 339050891, 7.69],
 [339050891, 339050892, 16.004],
 [339050892, 339050893, 21.079],
 [339050893, 2861669105, 15.701],
 [339050894, 339050895, 13.14],
 [339050895, 339050896, 26.243],
 [339050896, 339050897, 18.954],
 [339050897, 339050898, 27.015],
 [339050898, 339050899, 36.034],
 [339050899, 339050900, 33.964],
 [339050900, 5436700704, 14.203],
 [339050901, 2866714610, 20.683],
 [339050902, 339050903, 14.845],
 [339050903, 6052450981, 16.594],
 [339050904, 339050905, 26.81],
 [339050905, 339050906, 15.098],
 [339050906, 5118308277, 21.829],
 [339050906, 5118308279, 46.164],
 [339050907, 339050908, 31.261],
 [339050908, 339050909, 34.931],
 [339050909, 9125470649, 63.606],
 [339051476, 339051477, 13.951],
 [339051477, 339051478, 13.265],
 [339051478, 339051479, 13.278],
 [339051479, 339051480, 12.851],
 [339051480, 339051481, 11.57],
 [339051481, 339051482, 12.779],
 [339051482, 11242686018, 8.711],
 [339051538, 339051539, 10.594],
 [339051539, 339051540, 11.052],
 [339051540, 11242686024, 10.953],
 [339051541, 11242686009, 9.458],
 [339051592, 2866714604, 12.084],
 [339051593, 339051594, 23.288],
 [339051594, 339052028, 18.3],
 [339051594, 339052027, 27.713],
 [339051595, 339051596, 23.854],
 [339051596, 339051597, 39.364],
 [339051597, 339051598, 36.134],
 [339051598, 339051599, 35.958],
 [339051599, 339051600, 16.278],
 [339051600, 339051601, 11.287],
 [339051601, 2861669111, 13.515],
 [339051602, 11104980147, 20.649],
 [339051767, 339051593, 18.301],
 [339051768, 339051767, 16.677],
 [339051769, 339051768, 19.655],
 [339051784, 339051769, 19.949],
 [339051785, 339051784, 15.385],
 [339051786, 4971724758, 11.862],
 [339051995, 2866714633, 13.779],
 [339051996, 2866714633, 14.392],
 [339051997, 8766003550, 15.52],
 [339051998, 339051997, 14.926],
 [339051999, 2861669104, 37.097],
 [339052000, 2861666798, 40.011],
 [339052001, 339052000, 65.13],
 [339052027, 339051595, 16.225],
 [339052028, 339052029, 37.695],
 [339052029, 339052030, 42.6],
 [339052030, 339052031, 20.21],
 [339052031, 2866714626, 6.806],
 [339052032, 339051996, 30.305],
 [339052060, 11104980152, 12.617],
 [339053444, 2861666791, 48.72],
 [339053461, 1640472727, 33.598],
 [339053462, 339052060, 27.521],
 [339053474, 11104975397, 46.08],
 [339053482, 2866714620, 28.284],
 [339053515, 2866714603, 33.513],
 [339053516, 5333519688, 43.446],
 [339053606, 2866714631, 38.983],
 [339053606, 1168315989, 39.266],
 [339053607, 2866714615, 13.069],

In [12]:
with open(f"{ROOT_DIR}/data/training/node2vec/length.el", "w") as f:
    for edge in edges_list:
        f.write(f"{edge[0]} {edge[1]} {edge[2]}\n")