In [31]:
# Author        : Cow Cheng
# Date          : 30/06/2024
# Description   : Creating edgelist for basic nodes of edge from the raw edges information

In [32]:
import os
from pathlib import Path

ROOT_DIR = Path(os.getcwd()).parent.parent.absolute().__str__()

In [33]:
import pandas as pd

edges_df = pd.read_csv(filepath_or_buffer=f"{ROOT_DIR}/data/raw/osm_edges_info.csv")
edges_df

,u,v,key,osmid,oneway,lanes,name,highway,reversed,length,junction,bridge,ref,maxspeed,tunnel,access,service,area,geometry
0,33004487,10813125727,0,102506130,True,3.0,彌敦道 Nathan Road,primary,False,48.365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710536..."
1,33004487,9125470653,0,102506142,True,2.0,眾坊街 Public Square Street,secondary,False,1.845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710767..."
2,33004488,6357916699,0,102640426,True,3.0,彌敦道 Nathan Road,primary,False,11.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170737..."
3,33004488,1151084822,0,250489279,True,2.0,窩打老道 Waterloo Road,primary,False,10.668,intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170620..."
4,34971941,332248875,0,493744605,True,2.0,加士居道天橋 Gascoigne Road Flyover,trunk,False,43.118,NaN,yes,5.0,50.0,NaN,NaN,NaN,NaN,"LINESTRING (114.1673899 22.3106905, 114.167470..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7053,11880893092,11880893093,0,987256892,False,1.0,NaN,service,False,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171624..."
7054,11880893092,9125470644,0,987256892,False,1.0,NaN,service,True,7.362,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171708..."
7055,11880893093,11880893092,0,987256892,False,1.0,NaN,service,True,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.171624 22.3112437, 114.1716736..."
7056,11880893105,6521288995,0,150801664,False,NaN,石壁道 Cliff Road,residential,False,2.668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171830..."
7057,11880893105,4571243168,0,150801664,False,NaN,石壁道 Cliff Road,residential,True,2.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171863..."

In [34]:
edges_df = edges_df.loc[:, ["u", "v"]]
edges_df

                u            v
0        33004487  10813125727
1        33004487   9125470653
2        33004488   6357916699
3        33004488   1151084822
4        34971941    332248875
...           ...          ...
7053  11880893092  11880893093
7054  11880893092   9125470644
7055  11880893093  11880893092
7056  11880893105   6521288995
7057  11880893105   4571243168

[7058 rows x 2 columns]

In [35]:
edges_list = edges_df.values.tolist()
edges_list

[[33004487, 10813125727],
 [33004487, 9125470653],
 [33004488, 6357916699],
 [33004488, 1151084822],
 [34971941, 332248875],
 [245088212, 5135751883],
 [245088214, 8795975506],
 [274242693, 332243940],
 [274242694, 4501965596],
 [274242695, 3230279839],
 [274242705, 274242708],
 [274243013, 274243014],
 [274243014, 4773727051],
 [274243015, 8446511187],
 [274243016, 1181846034],
 [274243016, 8406879034],
 [274243017, 332242393],
 [274243018, 10566992992],
 [274243083, 332233448],
 [274243086, 5103661134],
 [274243086, 5103661131],
 [275908396, 10566992979],
 [275909256, 6374553590],
 [275909450, 7305838958],
 [275909450, 7305838955],
 [275935771, 7600185392],
 [275944916, 4773693609],
 [275945320, 9766361634],
 [275945418, 3230274782],
 [275945418, 9766365660],
 [275945538, 11235236460],
 [275945538, 10565387068],
 [275945653, 10726301482],
 [275945763, 10211498580],
 [275945763, 3919865758],
 [276372857, 6357916383],
 [276372857, 1151084911],
 [276373355, 6357916373],
 [276377951, 11235236461],
 [278948068, 1168316016],
 [278948068, 6370253655],
 [278948235, 10786928815],
 [278948607, 6271340027],
 [278948608, 1184307108],
 [278948608, 332254414],
 [278948609, 5255598058],
 [278948759, 2640738083],
 [278948832, 278948833],
 [278948833, 5255598053],
 [278948926, 6605085116],
 [278948926, 5012933247],
 [278948927, 5255598054],
 [278948927, 5255598074],
 [278948933, 439179847],
 [278948934, 8044314666],
 [278948999, 8044314690],
 [278948999, 278949000],
 [278949000, 278949001],
 [278949000, 278948999],
 [278949001, 278949000],
 [279076776, 8764628282],
 [279076776, 6550920169],
 [288991082, 9893206659],
 [288991083, 1172166327],
 [288991084, 6777002698],
 [288991123, 5029510785],
 [288991123, 1962192579],
 [288991127, 1962191597],
 [288991127, 5029510779],
 [288991129, 6052460354],
 [288991129, 1962191505],
 [288991131, 5118308284],
 [288991131, 1172166329],
 [288991132, 5118308285],
 [288991132, 5118308284],
 [288991202, 1172166326],
 [288991202, 5029495350],
 [288991212, 1295862825],
 [288991212, 493883921],
 [288991212, 1172166356],
 [288991213, 1295862822],
 [288991213, 1295862825],
 [288991214, 332232638],
 [288991214, 1295862839],
 [288991218, 1962192639],
 [288991218, 1962192676],
 [288991218, 6266394644],
 [288991219, 7154099552],
 [288991219, 5029510784],
 [288991219, 7154099554],
 [288991220, 5118308280],
 [288991220, 5029510780],
 [288991221, 1962191716],
 [288991221, 5118308280],
 [288991222, 5029510778],
 [288991222, 1962191597],
 [288991223, 5118308283],
 [288991223, 5118308286],
 [288991224, 8396898511],
 [288991224, 8081586137],
 [288991224, 6277201384],
 [288991681, 6176166200],
 [288991681, 6176166201],
 [288991682, 5118308267],
 [288991682, 7597784320],
 [288991682, 6039377373],
 [288991740, 2868161557],
 [288991741, 6364822864],
 [288991742, 2086704742],
 [288991742, 1182677912],
 [288991776, 3230279162],
 [288991777, 288991776],
 [288991796, 1168066109],
 [288991796, 9553739297],
 [288991859, 4353561377],
 [288991960, 288991859],
 [288991961, 1640472777],
 [288991961, 4858602289],
 [288992106, 1640472750],
 [288992206, 1640472741],
 [288994875, 1640472834],
 [288994875, 6886397805],
 [288994882, 5103568431],
 [288994882, 3200153661],
 [288994965, 7859225560],
 [288995086, 288995087],
 [288995087, 7859225566],
 [288995158, 3696283366],
 [288995217, 4858447071],
 [288996266, 7605392237],
 [288996266, 7605392232],
 [288996632, 288994882],
 [288996657, 6886397800],
 [289337490, 7575216225],
 [289337490, 4858447073],
 [308473171, 3230274026],
 [308473171, 3230274006],
 [308473172, 3230274170],
 [308473172, 3230274041],
 [308473173, 3230274023],
 [308473173, 3230274192],
 [308473175, 3230274366],
 [308473175, 3230274296],
 [308473176, 11134510106],
 [308473177, 1183092765],
 [308473177, 1151084890],
 [308473178, 11134374501],
 [308473179, 11134374504],
 [308473179, 11134374500],
 [308473179, 11134374497],
 [308473180, 6260814403],
 [308473180, 10804883515],
 [308473181, 3230277085],
 [308473182, 3230277492],
 [308473182, 3230277353],
 [308473183, 3230277355],
 [308473183, 3230277483],
 [308473185, 3230277719],
 [308473185, 3230277610],
 [308473186, 10825885939],
 [308473186, 10181859559],
 [308473186, 3230278485],
 [308473187, 3230278507],
 [308473188, 3230278501],
 [308473188, 11235236463],
 [308473189, 11196264030],
 [308473190, 3230280848],
 [308473190, 3230280999],
 [308473191, 3230280976],
 [308473191, 6364821073],
 [308473192, 3230281110],
 [308473193, 7205061372],
 [308473193, 7205061371],
 [308473195, 10250932206],
 [308473419, 4501975098],
 [308473420, 11232787248],
 [308473420, 11134510116],
 [308473422, 9953781642],
 [308473422, 9953781649],
 [308473423, 3176514544],
 [308473424, 7983295859],
 [308473424, 1151084860],
 [308473425, 9067018578],
 [308473426, 10825885963],
 [308473427, 3230280089],
 [308473429, 4862720941],
 [308473429, 11235236471],
 [308473546, 11248659125],
 [308473546, 1178971365],
 [308473546, 7205249277],
 [316731588, 10864964066],
 [316731590, 8789236514],
 [316731591, 8789236510],
 [316731592, 11406997370],
 [316731592, 4292132285],
 [316731592, 4292143906],
 [331258075, 1168315954],
 [331258075, 6374553575],
 [331258761, 7257383508],
 [331258761, 7257383490],
 [331258761, 4773779469],
 [331258764, 991294650],
 [331269944, 332251255],
 [331269982, 7242599215],
 [331269982, 6236308354],
 [331271265, 4773779481],
 [331271265, 4773716027],
 [331271928, 2389070841],
 [332227468, 4858602284],
 [332227468, 6364822991],
 [332227469, 332227468],
 [332227470, 332227469],
 [332227471, 9893504824],
 [332228049, 332233734],
 [332228049, 11229660893],
 [332228052, 5133915668],
 [332228052, 5133915667],
 [332228053, 4501965600],
 [332228053, 4501965601],
 [332228054, 5133915669],
 [332228055, 332228056],
 [332228056, 1182677867],
 [332228056, 332228057],
 [332228057, 1640472754],
 [332228057, 6886392425],
 [332228058, 4858594757],
 [332228059, 6886392427],
 [332228061, 7257383509],
 [332230218, 332228059],
 [332230894, 332227469],
 [332230895, 332230894],
 [332231811, 5118069110],
 [332231811, 6364822869],
 [332231898, 332231899],
 [332231899, 2868161561],
 [332231899, 2868161562],
 [332231922, 1182677790],
 [332231923, 332231922],
 [332231924, 332231923],
 [332231925, 332231924],
 [332232288, 2868161559],
 [332232290, 1182677772],
 [332232291, 9553739289],
 [332232291, 1182677796],
 [332232292, 288991961],
 [332232293, 332232292],
 [332232294, 6984911314],
 [332232295, 6984911302],
 [332232638, 1172166308],
 [332232638, 288991214],
 [332232732, 1956604873],
 [332232732, 1172166429],
 [332232732, 1956604863],
 [332232763, 332232764],
 [332232763, 6777002695],
 [332232763, 6776978979],
 [332232764, 332232765],
 [332232764, 332232763],
 [332232765, 332232766],
 [332232765, 332232764],
 [332232766, 5118308287],
 [332232766, 332232765],
 [332233250, 2868161565],
 [332233250, 5118069109],
 [332233253, 1168183739],
 [332233448, 9553739296],
 [332233448, 8154269374],
 [332233449, 9553739295],
 [332233450, 9553739291],
 [332233452, 5054347008],
 [332233734, 6776978971],
 [332234423, 332234424],
 [332234424, 9553982032],
 [332234425, 5118039272],
 [332234452, 332234425],
 [332235143, 9553982035],
 [332236247, 11242686010],
 [332236248, 3230279914],
 [332236250, 332236251],
 [332236251, 332236252],
 [332236252, 9553739290],
 [332236302, 332236591],
 [332236303, 5118039270],
 [332236564, 4944491510],
 [332236591, 5118039267],
 [332236658, 3230278791],
 [332236659, 493175666],
 [332236871, 4944491509],
 [332237002, 332237036],
 [332237036, 332236871],
 [332237192, 332237262],
 [332237199, 6374553508],
 [332237238, 332237192],
 [332237262, 4773727049],
 [332237288, 3270208461],
 [332238310, 11129305619],
 [332238480, 6389190616],
 [332238481, 11214989179],
 [332238481, 11214989167],
 [332239185, 5133960459],
 [332239185, 1180686912],
 [332240179, 11453018971],
 [332240248, 6389233142],
 [332240697, 1181846062],
 [332240700, 4773779472],
 [332241860, 5020696807],
 [332241861, 10566992988],
 [332241861, 10566992986],
 [332241870, 1172757618],
 [332241870, 332243716],
 [332241887, 8559094354],
 [332241978, 1181846107],
 [332241978, 7257383506],
 [332241980, 7257383504],
 [332242040, 6984393973],
 [332242040, 6984393970],
 [332242116, 4773779436],
 [332242333, 6576843537],
 [332242333, 7159249733],
 [332242336, 1161863870],
 [332242353, 4773779431],
 [332242393, 274243018],
 [332242579, 6370140256],
 [332242579, 7242599236],
 [332242620, 1181846148],
 [332242620, 4123241553],
 [332242753, 10848289257],
 [332242753, 1178971331],
 [332242754, 332251620],
 [332242754, 332242753],
 [332242755, 5035288921],
 [332242755, 1178971377],
 [332242765, 332243937],
 [332243000, 6264275960],
 [332243002, 332253240],
 [332243003, 288991796],
 [332243003, 1168066104],
 [332243005, 4860492619],
 [332243007, 7205257472],
 [332243088, 6357916689],
 [332243088, 6063179965],
 [332243513, 8273466961],
 [332243571, 332246717],
 [332243585, 4501974987],
 [332243716, 332241870],
 [332243716, 332241978],
 [332243937, 7257383515],
 [332243938, 7388719094],
 [332243939, 274242693],
 [332243940, 3230277782],
 [332243941, 7388719090],
 [332244016, 8272842740],
 [332244018, 3696262782],
 [332244341, 274243083],
 [332246270, 6176174000],
 [332246273, 1168380690],
 [332246717, 34971941],
 [332246756, 5133754167],
 [332247607, 6611651275],
 [332247608, 332248687],
 [332248212, 332248213],
 [332248213, 629161529],
 [332248214, 6702444348],
 [332248685, 332248700],
 [332248686, 5118308275],
 [332248687, 332248686],
 [332248700, 332243513],
 [332248875, 332248821],
 [332250570, 10786928832],
 [332251015, 3230283954],
 [332251015, 1168183637],
 [332251063, 5103661127],
 [332251063, 5103661126],
 [332251094, 11181151128],
 [332251094, 4860492620],
 [332251253, 332251620],
 [332251253, 11178396848],
 [332251253, 332242753],
 [332251254, 332251484],
 [332251254, 3391012792],
 [332251255, 9067018573],
 [332251256, 7205249279],
 [332251256, 7207625693],
 [332251257, 332251256],
 [332251257, 10181839350],
 [332251373, 1182677910],
 [332251374, 3230283899],
 [332251374, 3230283560],
 [332251375, 9067018588],
 [332251375, 9067018571],
 [332251376, 7207625692],
 [332251377, 3696264071],
 [332251377, 10198945171],
 [332251377, 10181839356],
 [332251378, 3691165231],
 [332251484, 10203538055],
 [332251484, 1442088610],
 [332251500, 9135398607],
 [332251605, 3391012791],
 [332251620, 6236308350],
 [332251664, 332251373],
 [332251664, 11177196758],
 [332251667, 7454080527],
 [332251667, 5133880779],
 [332251683, 332251682],
 [332251828, 11134374487],
 [332252247, 7597823394],
 [332252247, 1182950283],
 [332253240, 1168315922],
 [332253240, 8438621459],
 [332253310, 3230275941],
 [332253310, 3230275869],
 [332253311, 3230276002],
 [332253311, 3230275952],
 [332253312, 3230275924],
 [332253312, 3230276003],
 [332253313, 3230276216],
 [332253329, 7159812414],
 [332253329, 1185400641],
 [332253331, 10825885941],
 [332253333, 8192075924],
 [332253494, 6880235602],
 [332253494, 4501974988],
 [332253631, 3230274239],
 [332254414, 4355051555],
 [332254415, 3691187062],
 [332254415, 1162875764],
 [334647674, 2861669114],
 [334647674, 11104977107],
 [334647889, 2861666795],
 [334647890, 11104980151],
 [334647891, 2861666800],
 [334647892, 2861669103],
 [334647893, 334647894],
 [334647894, 2861669109],
 [334647895, 11104980142],
 [334647896, 11104980135],
 [334647897, 4502010708],
 [334647899, 334652200],
 [334648400, 1168315957],
 [334648405, 334648629],
 [334648625, 6989122616],
 [334648625, 1168315919],
 [334648626, 6357916691],
 [334648627, 1168315967],
 [334648629, 334648627],
 [334648722, 334651133],
 [334648723, 334651132],
 [334648727, 2861669101],
 [334649581, 11081087759],
 [334649727, 334649852],
 [334649728, 8767974619],
 [334649729, 2868161551],
 [334649849, 334650280],
 [334649850, 4501965609],
 [334649851, 2866714638],
 [334649851, 2866714639],
 [334649852, 334649851],
 [334650236, 11104980140],
 [334650280, 2866714635],
 [334650280, 2866714634],
 [334650313, 339053515],
 [334650313, 339053461],
 [334650570, 1172166386],
 [334650572, 334650573],
 [334650573, 334650574],
 [334650574, 9125470648],
 [334650575, 1168315927],
 [334650654, 9125470651],
 [334650656, 1172166367],
 [334650656, 7553815435],
 [334650889, 334650890],
 [334650890, 334650891],
 [334650891, 6370217679],
 [334650892, 334650893],
 [334650893, 4501965605],
 [334650906, 7859225563],
 [334650907, 2868161575],
 [334650908, 8767974621],
 [334651084, 2868161570],
 [334651084, 2868161571],
 [334651129, 334651084],
 [334651130, 7539621741],
 [334651131, 7270937151],
 [334651132, 334648722],
 [334651133, 11105007273],
 [334651138, 2868161552],
 [334651139, 2868161550],
 [334651140, 11104975395],
 [334651141, 11104975391],
 [334651141, 11104975394],
 [334651192, 8909807442],
 [334651192, 7605392237],
 [334651193, 11462479066],
 [334651193, 7605409499],
 [334651194, 334651193],
 [334651195, 5052279540],
 [334651195, 6776978974],
 [334651201, 334651131],
 [334651203, 334651201],
 [334652024, 334652025],
 [334652025, 2832941849],
 [334652026, 11104977129],
 [334652027, 11104980131],
 [334652029, 11104980139],
 [334652030, 11104980143],
 [334652032, 11104980146],
 [334652033, 2861669108],
 [334652034, 334652035],
 [334652035, 334652036],
 [334652036, 334652037],
 [334652037, 334652038],
 [334652038, 339053444],
 [334652200, 11104977130],
 [334652201, 334652202],
 [334652202, 2832941850],
 [334653504, 334650908],
 [334653511, 2868161573],
 [339050813, 8766021731],
 [339050887, 7553034785],
 [339050887, 339050888],
 [339050888, 339050889],
 [339050889, 2861669102],
 [339050890, 339050891],
 [339050891, 339050892],
 [339050892, 339050893],
 [339050893, 2861669105],
 [339050894, 339050895],
 [339050895, 339050896],
 [339050896, 339050897],
 [339050897, 339050898],
 [339050898, 339050899],
 [339050899, 339050900],
 [339050900, 5436700704],
 [339050901, 2866714610],
 [339050902, 339050903],
 [339050903, 6052450981],
 [339050904, 339050905],
 [339050905, 339050906],
 [339050906, 5118308277],
 [339050906, 5118308279],
 [339050907, 339050908],
 [339050908, 339050909],
 [339050909, 9125470649],
 [339051476, 339051477],
 [339051477, 339051478],
 [339051478, 339051479],
 [339051479, 339051480],
 [339051480, 339051481],
 [339051481, 339051482],
 [339051482, 11242686018],
 [339051538, 339051539],
 [339051539, 339051540],
 [339051540, 11242686024],
 [339051541, 11242686009],
 [339051592, 2866714604],
 [339051593, 339051594],
 [339051594, 339052028],
 [339051594, 339052027],
 [339051595, 339051596],
 [339051596, 339051597],
 [339051597, 339051598],
 [339051598, 339051599],
 [339051599, 339051600],
 [339051600, 339051601],
 [339051601, 2861669111],
 [339051602, 11104980147],
 [339051767, 339051593],
 [339051768, 339051767],
 [339051769, 339051768],
 [339051784, 339051769],
 [339051785, 339051784],
 [339051786, 4971724758],
 [339051995, 2866714633],
 [339051996, 2866714633],
 [339051997, 8766003550],
 [339051998, 339051997],
 [339051999, 2861669104],
 [339052000, 2861666798],
 [339052001, 339052000],
 [339052027, 339051595],
 [339052028, 339052029],
 [339052029, 339052030],
 [339052030, 339052031],
 [339052031, 2866714626],
 [339052032, 339051996],
 [339052060, 11104980152],
 [339053444, 2861666791],
 [339053461, 1640472727],
 [339053462, 339052060],
 [339053474, 11104975397],
 [339053482, 2866714620],
 [339053515, 2866714603],
 [339053516, 5333519688],
 [339053606, 2866714631],
 [339053606, 1168315989],
 [339053607, 2866714615],
 [339053608, 2866714601],
 [339053635, 2866714495],
 [339053698, 2866714602],
 [339053699, 2866714618],
 [339053700, 2866714625],
 [339053701, 2866714630],
 [339054218, 9678646965],
 [339054219, 9772967563],
 [339054219, 9773097328],
 [339054265, 4773693583],
 [339054265, 4773693580],
 [339054267, 4773693576],
 [339054322, 6389190615],
 [339054322, 4353541537],
 [339054415, 9197567330],
 [339054415, 339054265],
 [339054417, 10290775981],
 [339054417, 8912728888],
 [339054418, 4773331331],
 [339054470, 6895725701],
 [339054471, 339054470],
 [339054472, 6991262053],
 [339054473, 339054472],
 [339054474, 4773693593],
 [339054475, 1152803603],
 [339054476, 339054475],
 [412685610, 4335274775],
 [412685610, 332242754],
 [412685611, 6990193881],
 [419752768, 332251063],
 [419752768, 3391012787],
 [419763802, 493178393],
 [420028543, 6389233143],
 [420028545, 10786928860],
 [420028546, 6680793616],
 [420028546, 1178971337],
 [439179845, 8044314673],
 [439179846, 439179845],
 [439179847, 8044314665],
 [439179847, 3691187055],
 [439179852, 1184307124],
 [439179852, 6605085116],
 [439180903, 5020395154],
 [439180903, 5118402531],
 [439180917, 5020395132],
 [439180917, 7207551573],
 [439989637, 8044314778],
 [439989637, 8044314775],
 [439989638, 439989639],
 [439989638, 8044314778],
 [439989639, 1184307086],
 [439989639, 439989638],
 [452738352, 2772111132],
 [452738352, 2772111130],
 [452738352, 485668899],
 [452738358, 9671393069],
 [452738358, 9671393068],
 [484136620, 4858513442],
 [484136660, 5118372418],
 [484136661, 4464851535],
 [484136661, 9926356984],
 [485668899, 1636685510],
 [485668899, 452738352],
 [493172566, 9125470647],
 [493172566, 9125470640],
 [493175666, 274242695],
 [493176074, 9395491137],
 [493177679, 6328079477],
 [493177743, 11217387603],
 [493177743, 11217387598],
 [493177900, 8556147235],
 [493177903, 1640472795],
 [493178012, 1172757683],
 [493178393, 6705233244],
 [493178530, 332251094],
 [493179429, 5554287539],
 [493179467, 4860691744],
 [493883391, 6886392472],
 [493883921, 288991212],
 [493883921, 1172166363],
 [513354004, 513354006],
 [513354006, 4335274776],
 [513355463, 3692616229],
 [513355469, 3696283369],
 [513355473, 1784785780],
 [513355478, 7859225556],
 [513355483, 7859225557],
 [513355489, 6284393693],
 [513355498, 3200166661],
 [513355507, 513355498],
 [513355518, 513355507],
 [513355523, 513355518],
 [629161521, 6702444349],
 [629161529, 332248214],
 [629539173, 339051786],
 [629539174, 629539173],
 [629539175, 6327429712],
 [629539198, 4858594756],
 [653112498, 6984479460],
 [653112507, 10219928291],
 [653112507, 11453007866],
 [653112508, 10848289299],
 [653112508, 6984479448],
 [660864272, 11153075976],
 [660864272, 10877247414],
 [660864273, 11222686200],
 [660864273, 11153075977],
 [660864278, 11153075931],
 [660864279, 11217924633],
 [660864279, 11222686175],
 [660864280, 653112508],
 [660864280, 6374553455],
 [675264194, 6702368682],
 [675264194, 675264196],
 [675264196, 2772111145],
 [675264197, 675264198],
 [675264198, 2772111152],
 [675264198, 2772111168],
 [675264198, 2772111173],
 [675264200, 11183239347],
 [675264252, 675264255],
 [675264255, 6244674905],
 [675264358, 675264194],
 [675264359, 675264360],
 [675264360, 675264363],
 [675264363, 2772111185],
 [675264366, 2772111186],
 [675264369, 8258544333],
 [675264372, 7187094413],
 [675264372, 8258544339],
 [675264375, 675264378],
 [675264378, 8258544330],
 [675264511, 8258544560],
 [675264514, 10796686376],
 [675264517, 6705233489],
 [675264520, 6766651819],
 [675264523, 9892950978],
 [675264565, 6702368659],
 [675264565, 7709818207],
 [675264566, 1636641311],
 [675264566, 6705233561],
 [675264567, 11107138075],
 [675264567, 6702368661],
 [804106404, 8831102457],
 [804106404, 1222131060],
 [804106424, 1152660784],
 [804106442, 10250472468],
 [804106457, 6360547164],
 [804106457, 1208936439],
 [804106896, 1208936447],
 [804106904, 4282080343],
 [804106909, 3909056819],
 [804106917, 6244674904],
 [804106917, 804106924],
 [804106924, 3909056816],
 [804106924, 5102154188],
 [804106932, 6705233666],
 [804107000, 7142251278],
 [804107000, 6705233115],
 [804107013, 11234193740],
 [804107016, 4282080345],
 [804107188, 1152660828],
 [804107193, 4336716150],
 [804107211, 9415492740],
 [804107211, 1222130515],
 [804107226, 5255613889],
 [804107226, 5429072337],
 [804107233, 5255613893],
 [804107233, 5429072334],
 [804107237, 5102113130],
 [804107241, 10211498585],
 [804107241, 10799551065],
 [804107253, 4353595939],
 [804107264, 7983295860],
 [804108014, 6705233489],
 [804108014, 8258544693],

In [36]:
with open(f"{ROOT_DIR}/data/training/node2vec/basic.el", "w") as f:
    for edge in edges_list:
        f.write(f"{edge[0]} {edge[1]}\n")